<html>
    <!DOCTYPE html>
<html>
<body background="map.jpg">
<form action="/project/solve.php" method="POST">
cost&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name = "Ycost" value = "<?php     $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10); echo $contents; ?>"><input type = "text" name="cost" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); echo $contents; ?>" size="1">(0 = ignore 1 = at least 2 = at most)
<br><br>
carlories&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="Ycarlories" value = "<?php $myfile = fopen('out.txt', 'r');      $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="carlories" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size="1">
<br><br>
proteins&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="Yproteins" value = "<?php $myfile = fopen('out.txt', 'r');      $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="proteins" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size="1">
<br><br>
carbohydrates:<input type="text" name="Ycarbohydrates" value = "<?php $myfile = fopen('out.txt', 'r');      $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="carbohydrates" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size="1">
<br><br>
vitamin A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="YvitaminA" value = "<?php $myfile = fopen('out.txt', 'r');      $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="vitaminA" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size="1">
<br><br> 
calcium &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="Ycalcium" value = "<?php $myfile = fopen('out.txt', 'r');      $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="calcium" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10); echo $contents; ?>" size="1">
<br><br>
fat&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="Yfat" value = "<?php $myfile = fopen('out.txt', 'r');      $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="fat" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size="1">
<br><br>
cholesterol&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="Ycholesterol" value = "<?php $myfile = fopen('out.txt', 'r');      $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="cholesterol" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size="1">
<br><br> 
sodium&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="Ysodium" value = "<?php $myfile = fopen('out.txt', 'r');      $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="sodium" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size="1">
<br><br>
fiber&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="Yfiber" value = "<?php $myfile = fopen('out.txt', 'r');$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="fiber" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size="1">
<br><br>
vitamin C&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="YvitaminC" value = "<?php $myfile = fopen('out.txt', 'r');      $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents;?>"><input type = "text" name="vitaminC" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size="1">

<br>
<br>
<br>
objective: <input type = "text" name="objective" value = "<?php $myfile = fopen('out.txt', 'r'); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10); $contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);$contents = fgets($myfile, 10);echo $contents; ?>" size = 1;>
<br>
<input type="submit" value="Submit">
</form>
<?php
  /*$a = $_POST['a'];
  $b = $_POST['b'];
  $c = $_POST['c'];
  $txt = ".txt";
  $neutrition = "neutrition.txt";
  $neutrition = $a.$neutrition;
  $a = $a.$txt;

  $myfile = fopen($a, "w"); 
  fwrite($myfile,$b);
  fwrite($myfile,",");
  fwrite($myfile,$c);
  fclose($myfile);
  $answer = shell_exec("./nutritionTable in out");*/
?>
<script type="text/javascript">
	function to_search() {
		for (var i = 10000; i >= 0; i--) {
			
		}
		//window.open('/project/search_1117_ui.php','false')
	}

</script>

</body>
</html>
